(()=>{'use strict';
const T=THREE,data=JSON.parse(document.getElementById('structure-data').textContent),complex=JSON.parse(document.getElementById('complex-data').textContent),overlay=document.getElementById('animation'),ctx=overlay.getContext('2d'),axisCanvas=document.getElementById('axes'),axisCtx=axisCanvas.getContext('2d');
/*__CARTOON__*/
/*__SPHERE_SHADERS__*/
const v=a=>new T.Vector3(...a),smooth=x=>{x=T.MathUtils.clamp(x,0,1);return x*x*(3-2*x);},mean=ps=>ps.reduce((a,p)=>a.add(p),new T.Vector3()).multiplyScalar(1/ps.length);
const renderer=new T.WebGLRenderer({antialias:true,alpha:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor('#ffffff',1);document.getElementById('stage').appendChild(renderer.domElement);
const scene=new T.Scene(),camera=new T.OrthographicCamera(-300,500,260,-260,1,2000);camera.position.set(0,0,700);scene.add(new T.HemisphereLight(0xffffff,0x929cad,2));const light=new T.DirectionalLight(0xffffff,2.4);light.position.set(-200,300,600);scene.add(light);
const world=new T.Group(),upper=new T.Group(),lower=new T.Group(),head=new T.Group(),actors=new T.Group();scene.add(world);world.add(upper,lower,actors);lower.add(head);const hp=v(complex.headPivot);head.position.copy(hp);
const colors={'23S':'#c49547','5S':'#b36856',LP:'#7586b1','16S':'#489991',SP:'#607dac'},chains=[],coords=new Int16Array(Uint8Array.from(atob(data.coordinates),c=>c.charCodeAt(0)).buffer),headFlags=Uint8Array.from(atob(complex.headFlags),c=>c.charCodeAt(0));
function makeRibo(ch,group,pos,trace){if(!pos.length||trace.length<2)return;const geo=cartoonGeometry({...ch,trace});if(group===head)geo.translate(-hp.x,-hp.y,-hp.z);const cartoon=new T.Mesh(geo,new T.MeshStandardMaterial({color:colors[ch.type],roughness:.7,side:T.DoubleSide,transparent:true,opacity:.23,depthWrite:false}));group.add(cartoon);const p=new Float32Array(pos);if(group===head)for(let i=0;i<p.length;i+=3){p[i]-=hp.x;p[i+1]-=hp.y;p[i+2]-=hp.z;}const g=new T.BufferGeometry();g.setAttribute('position',new T.BufferAttribute(p,3));g.setAttribute('atomRadius',new T.BufferAttribute(new Float32Array(p.length/3).fill(1.55),1));const mat=new T.ShaderMaterial({uniforms:{tint:{value:new T.Color(colors[ch.type])},fade:{value:1},pixelsPerUnit:{value:1},depthRange:{value:1999},alpha:{value:.14}},vertexShader:vertex,fragmentShader:'uniform float alpha;'+fragment.replace('vec4(color,1.0)','vec4(color,alpha)'),transparent:true,depthWrite:false,extensions:{fragDepth:true}});const spheres=new T.Points(g,mat);group.add(spheres);cartoon.userData.part=ch.type==='LP'?'large-protein':ch.type==='SP'?'small-protein':ch.type==='16S'?'small':'large';chains.push({cartoon,spheres,part:cartoon.userData.part,baseColor:colors[ch.type]});}
for(const ch of data.chains){const pos=Array.from(coords.slice(ch.offset*3,(ch.offset+ch.count)*3),x=>x/10);if(ch.type==='16S'){const a=[],b=[];for(let i=0;i<ch.count;i++)(headFlags[i]?a:b).push(...pos.slice(i*3,i*3+3));makeRibo(ch,head,a,ch.trace.filter(r=>r[0]>=926&&r[0]<=1391));makeRibo(ch,lower,b,ch.trace.filter(r=>r[0]<926||r[0]>1391));}else {const isHead=/protein S(3|7|9|10|13|14|19)$/.test(ch.name);makeRibo(ch,isHead?head:ch.type==='SP'?lower:upper,pos,ch.trace);}}
const mat=(color,extra={})=>new T.MeshStandardMaterial({color,roughness:.55,side:T.DoubleSide,...extra});
// One continuous ribbon plus ribose pentagons and purine/pyrimidine rings.
// Ring positions inside the deposited complex use experimental atom coordinates.
function rnaGeometry(res,color){const positions=[],cols=[],indices=[];const tint=new T.Color(color);function add(p,c){positions.push(p.x,p.y,p.z);cols.push(c.r,c.g,c.b);return positions.length/3-1;}function triangle(a,b,c,tint){indices.push(add(a,tint),add(b,tint),add(c,tint));}function polygon(ps,c){if(ps.length<3)return;const center=mean(ps);for(let i=0;i<ps.length;i++)triangle(center,ps[i],ps[(i+1)%ps.length],c);}
 const path=res.filter(r=>r.atoms["C4'"]);const curve=new T.CatmullRomCurve3(path.map(r=>v(r.atoms["C4'"])),false,'centripetal');const rings=[];let prev=null;for(let k=0;k<=(path.length-1)*4;k++){const f=k/4,i=Math.min(Math.floor(f),path.length-2),mix=f-i,t=f/(path.length-1),p=curve.getPoint(t),tangent=curve.getTangent(t);const r=path[Math.round(f)];let guide=v(r.atoms.N9||r.atoms.N1||r.atoms["C1'"]).sub(v(r.atoms["C4'"]));guide.addScaledVector(tangent,-guide.dot(tangent)).normalize();if(prev&&guide.dot(prev)<0)guide.negate();prev=guide.clone();const normal=new T.Vector3().crossVectors(tangent,guide).normalize(),fade=r.fade??1,c=tint.clone().lerp(new T.Color('white'),1-fade);rings.push(Array.from({length:6},(_,j)=>add(p.clone().addScaledVector(guide,1.5*Math.cos(j*Math.PI/3)).addScaledVector(normal,.26*Math.sin(j*Math.PI/3)),c)));}for(let k=0;k<rings.length-1;k++)for(let j=0;j<6;j++){const a=rings[k][j],b=rings[k][(j+1)%6],c=rings[k+1][j],d=rings[k+1][(j+1)%6];indices.push(a,b,c,b,d,c);}
 for(const r of res){const a=r.atoms,fade=r.fade??1;const c=tint.clone().lerp(new T.Color('white'),1-fade);const sugar=['O4',"C1'","C2'","C3'","C4'"].map(k=>a[k==='O4'?"O4'":k]).filter(Boolean).map(v);polygon(sugar,c.clone().lerp(new T.Color('white'),.3));for(const keys of [['N1','C2','N3','C4','C5','C6'],...(a.N9?[['N9','C8','N7','C5','C4']]:[])]){const ps=keys.map(k=>a[k]).filter(Boolean).map(v);polygon(ps,c.clone().multiplyScalar(.8));}const start=v(a["C1'"]||a["C4'"]),end=v(a.N9||a.N1||a["C4'"]);const side=new T.Vector3(0,.22,.12);triangle(start.clone().add(side),start.clone().sub(side),end.clone().add(side),c);triangle(start.clone().sub(side),end.clone().sub(side),end.clone().add(side),c);}
 const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(positions,3));g.setAttribute('color',new T.Float32BufferAttribute(cols,3));g.setIndex(indices);g.computeVertexNormals();return g;}
function rna(c,color,early=null){const group=new T.Group();const geo=rnaGeometry(c.res,color);if(early){const lookup=new Map(early.res.map(r=>[r.seq,r]));const matched=c.res.map(r=>({ ...r,atoms:Object.fromEntries(Object.entries(r.atoms).map(([key,value])=>[key,lookup.get(r.seq)?.atoms[key]||value]))}));const eg=rnaGeometry(matched,color);if(eg.attributes.position.count!==geo.attributes.position.count)throw Error('RNA morph topology mismatch');geo.morphAttributes.position=[eg.attributes.position];geo.morphAttributes.normal=[eg.attributes.normal];geo.morphTargetsRelative=false;}const mesh=new T.Mesh(geo,mat('#ffffff',{vertexColors:true}));group.add(mesh);actors.add(group);return {group,mesh,res:c.res};}
const aRNA=rna(complex.bound.A,'#2a927f',complex.early.A),pRNA=rna(complex.bound.P,'#ca8a48'),eRNA=rna(complex.bound.E,'#9b86b1');
function atom(c,seq,name="C4'"){return v(c.res.find(r=>r.seq===seq).atoms[name]);}const aTip=atom(complex.bound.A,76),pTip=atom(complex.bound.P,77),aAnti=mean([34,35,36].map(s=>atom(complex.bound.A,s))),pAnti=mean([35,36,37].map(s=>atom(complex.bound.P,s))),eAnti=mean([35,36,37].map(s=>atom(complex.bound.E,s)));const direction=aAnti.clone().sub(pAnti).normalize();
const transcript=JSON.parse(JSON.stringify(complex.bound.mRNA));const first=transcript.res[0],last=transcript.res.at(-1);function extend(base,sign){const anchor=v(base.atoms["C4'"]);return Array.from({length:42},(_,i)=>{const n=i+1,delta=direction.clone().multiplyScalar(sign*n*5.8).add(new T.Vector3(0,Math.sin(n*.36)*3,Math.sin(n*.27)*5));return {seq:sign<0?-n:18+n,name:base.name,fade:Math.pow(1-n/43,1.7),atoms:Object.fromEntries(Object.entries(base.atoms).map(([k,a])=>[k,v(a).add(delta).toArray()]))};});}transcript.res=[...extend(first,-1).reverse(),...transcript.res,...extend(last,1)];const mrna=rna(transcript,'#6689bf');
const efTrace=complex.early.EF_Tu.res.filter(r=>r.atoms.CA).map(r=>[r.seq,...r.atoms.CA,...(r.atoms.O||r.atoms.CA),'C']);const efTu=new T.Mesh(cartoonGeometry({type:'LP',trace:efTrace}),mat('#8296b9',{transparent:true,opacity:.65,depthWrite:false}));actors.add(efTu);
// A nascent chain is an unfolded backbone, not preassigned helices or sheets.
const l23=data.chains.find(c=>/protein L23$/.test(c.name));const exit=l23?v(l23.center):pTip.clone().add(new T.Vector3(-50,50,0));const out=exit.clone().sub(pTip).normalize();const peptide=new T.Mesh(new T.BufferGeometry(),mat('#ffffff',{vertexColors:true}));actors.add(peptide);const aa=new T.Mesh(new T.SphereGeometry(2.7,14,10),mat('#c95e83'));actors.add(aa);
function peptideGeometry(tip,t){const points=[tip.clone(),pTip.clone().lerp(exit,.3),pTip.clone().lerp(exit,.7),exit.clone()];for(let i=1;i<55;i++)points.push(exit.clone().addScaledVector(out,i*4.1).add(new T.Vector3(Math.sin(i*.38+t*.4)*4,Math.sin(i*.31)*4,Math.cos(i*.3+t*.4)*5)));const curve=new T.CatmullRomCurve3(points,false,'centripetal'),geo=new T.TubeGeometry(curve,230,1.1,4,false);const frames=curve.computeFrenetFrames(230,false),pos=geo.getAttribute('position'),co=[];for(let i=0;i<=230;i++){const pt=curve.getPointAt(i/230);for(let j=0;j<=4;j++){const q=pt.clone().addScaledVector(frames.normals[i],Math.cos(j*Math.PI/2)*2.0).addScaledVector(frames.binormals[i],Math.sin(j*Math.PI/2)*.25);pos.setXYZ(i*5+j,q.x,q.y,q.z);}}geo.computeVertexNormals();for(let i=0;i<pos.count;i++){const f=i/pos.count;const fade=f<.09?.55:Math.max(0,1-Math.pow((f-.09)/.91,1.6));const c=new T.Color('#cb7395').lerp(new T.Color('white'),1-fade);co.push(c.r,c.g,c.b);}geo.setAttribute('color',new T.Float32BufferAttribute(co,3));return geo;}
const site16=mean(complex.anchors['16S'].map(v)),site23=mean(complex.anchors['23S'].map(v));function halo(pos,col){const mesh=new T.Mesh(new T.SphereGeometry(4,18,12),mat(col,{transparent:true,opacity:.6,depthWrite:false,wireframe:true}));mesh.position.copy(pos);actors.add(mesh);return mesh;}const decode=halo(site16,'#389b81'),catalysis=halo(site23,'#c39547');
const pairGeom=new T.BufferGeometry();pairGeom.setAttribute('position',new T.Float32BufferAttribute(new Float32Array(18),3));const pairing=new T.LineSegments(pairGeom,new T.LineDashedMaterial({color:'#427b70',dashSize:1,gapSize:.7}));actors.add(pairing);
function transform(src){const e=src.rotation,m=new T.Matrix4().set(e[0],e[1],e[2],0,e[3],e[4],e[5],0,e[6],e[7],e[8],0,0,0,0,1);return {q:new T.Quaternion().setFromRotationMatrix(m),p:v(src.translation)};}const AP=transform(complex.transforms.AP),PE=transform(complex.transforms.PE);function setTransform(group,tr,f){group.quaternion.identity().slerp(tr.q,f);group.position.copy(tr.p).multiplyScalar(f);}const identity=new T.Quaternion();
// Orient the deposited mRNA 5′→3′ direction toward the upper right.
const y=new T.Vector3(0,1,0),x=direction.clone().addScaledVector(y,-direction.dot(y)).normalize(),z=new T.Vector3().crossVectors(x,y);const basis=new T.Matrix4().makeBasis(x,y,z);const initial=new T.Quaternion().setFromRotationMatrix(basis).invert().premultiply(new T.Quaternion().setFromAxisAngle(new T.Vector3(0,0,1),.93));const rotation=initial.clone();
let W=innerWidth,H=innerHeight,unit=1,zoom=1,time=0,previous=0,paused=false,mode='cartoon',dragging=false,lastPointer=null,shell=false,oldPhase=-1,lastPeptide=-1,phase=0;const period=22;
const titles=['01 · Initial selection','02 · GTP hydrolysis & accommodation','03 · Peptide bond formation','04 · Hybrid states & subunit rotation','05 · Translocation & reset'];const descriptions=['EF-Tu delivers A/T-state tRNA; its anticodon samples the mRNA codon.','EF-Tu leaves; the tRNA elbow and 3′-CCA end move into the A/A position.','The 23S rRNA active site supports peptide transfer from P-site to A-site tRNA.','Acceptor ends move first; anticodons stay in place as the 30S subunit rotates.','EF-G and GTP support translocation: A → P, P → E, one codon forward.'];

function resize(){W=innerWidth;H=innerHeight;unit=Math.min(W/1280,H/800);renderer.setSize(W,H);const d=renderer.getPixelRatio();overlay.width=W*d;overlay.height=H*d;overlay.style.width=W+'px';overlay.style.height=H+'px';ctx.setTransform(d,0,0,d,0,0);axisCanvas.width=100*d;axisCanvas.height=100*d;axisCtx.setTransform(d,0,0,d,0,0);layout();}function layout(){const h=450/zoom,ww=h*W/H;camera.left=-ww*.37;camera.right=ww*.63;camera.top=h*.44;camera.bottom=-h*.56;camera.updateProjectionMatrix();for(const ch of chains)ch.spheres.material.uniforms.pixelsPerUnit.value=H/h*renderer.getPixelRatio();document.body.dataset.zoom=zoom.toFixed(3);}
function screen(p,group=actors){const q=group.localToWorld(p.clone()).project(camera);return [(q.x+1)*W/2,(1-q.y)*H/2];}function txt(s,x,y,size=12,c='#617b7e'){ctx.font=`${size}px -apple-system,BlinkMacSystemFont,"PingFang SC",sans-serif`;ctx.fillStyle=c;ctx.fillText(s,x,y,Math.max(60,W-x-20));}function stroke(ps,c,w=1){ctx.strokeStyle=c;ctx.lineWidth=w;ctx.beginPath();ps.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.stroke();}function label(s,sub,p,y,c,group=actors){const xy=screen(p,group),x=W*.77;stroke([xy,[x-26,y-5],[x-12,y-5]],c,.65);ctx.fillStyle=c;ctx.beginPath();ctx.arc(...xy,2,0,Math.PI*2);ctx.fill();txt(s,x,y,Math.max(11,13*unit),c);txt(sub,x,y+17,Math.max(9,10*unit),'#91a2a4');}
function drawAxes(){axisCtx.clearRect(0,0,100,100);const axes=[['X','#c86468',new T.Vector3(1,0,0)],['Y','#63a57d',new T.Vector3(0,1,0)],['Z','#6c87cf',new T.Vector3(0,0,1)]].map(([n,c,p])=>({n,c,p:p.applyQuaternion(rotation)})).sort((a,b)=>a.p.z-b.p.z);for(const a of axes){axisCtx.strokeStyle=a.c;axisCtx.fillStyle=a.c;axisCtx.lineWidth=3;axisCtx.beginPath();axisCtx.moveTo(48,51);axisCtx.lineTo(48+a.p.x*31,51-a.p.y*31);axisCtx.stroke();axisCtx.font='11px sans-serif';axisCtx.fillText(a.n,44+a.p.x*41,55-a.p.y*41);}axisCanvas.dataset.orientation=rotation.toArray().join(',');}
let hovered=null,hoverPointer=null,lastPick=0,labelHover=null,pinnedPart=null;
const labelLayer=document.createElement('div');labelLayer.id='structure-labels';labelLayer.setAttribute('aria-label','Interactive structure labels');document.body.appendChild(labelLayer);
const labelButtons=new Map();let currentLabels=new Set();
function registerLabel(id,name,sub,f){
 currentLabels.add(id);let button=labelButtons.get(id);
 if(!button){button=document.createElement('button');button.className='structure-label-hit';button.dataset.part=id;
 button.addEventListener('pointerenter',()=>{labelHover=id;hoverPointer=null;});
 button.addEventListener('pointerleave',()=>{if(labelHover===id)labelHover=null;});
 button.addEventListener('focus',()=>{labelHover=id;});
 button.addEventListener('blur',()=>{if(labelHover===id)labelHover=null;});
 button.addEventListener('click',()=>{pinnedPart=pinnedPart===id?null:id;});
 labelLayer.appendChild(button);labelButtons.set(id,button);}
 button.hidden=false;button.style.top=(H*f-17)+'px';button.setAttribute('aria-label',name+'. '+sub);button.title='Hover to highlight · Click to pin / unpin';button.setAttribute('aria-pressed',String(pinnedPart===id));button.dataset.active=String(hovered===id);
}

const picker=new T.Raycaster();
const hoverObjects=[[aRNA.mesh,'a-trna'],[pRNA.mesh,'p-trna'],[eRNA.mesh,'e-trna'],[mrna.mesh,'mrna'],[peptide,'peptide'],[efTu,'ef-tu'],[aa,'amino-acid']];
for(const [mesh,id] of hoverObjects)mesh.userData.part=id;
function pickPart(now){
 if(dragging){hovered=null;return;}if(labelHover||pinnedPart){hovered=labelHover||pinnedPart;return;}if(!hoverPointer||hoverPointer.x>W*.75){hovered=null;return;}
 if(now-lastPick<90)return;lastPick=now;
 const [mx,my]=[hoverPointer.x,hoverPointer.y];
 for(const [id,pos] of [['ptc',site23],['decoding',site16]]){const xy=screen(pos);if(Math.hypot(xy[0]-mx,xy[1]-my)<17){hovered=id;return;}}
 picker.setFromCamera(new T.Vector2(mx/W*2-1,1-my/H*2),camera);
 const visible=hoverObjects.filter(([m])=>m.visible&&m.parent.visible&&m.material.opacity>.08).map(([m])=>m);
 let hits=picker.intersectObjects(visible,false);
 if(!hits.length){const path=mrna.res.filter(r=>(r.fade??1)>.10).map(r=>screen(v(r.atoms["C4'"]),mrna.group));for(let i=1;i<path.length;i++){const a=path[i-1],b=path[i],dx=b[0]-a[0],dy=b[1]-a[1],u=T.MathUtils.clamp(((mx-a[0])*dx+(my-a[1])*dy)/(dx*dx+dy*dy||1),0,1);if(Math.hypot(mx-a[0]-u*dx,my-a[1]-u*dy)<7){hovered='mrna';return;}}}
 if(!hits.length)hits=picker.intersectObjects(chains.map(c=>c.cartoon),false);
 hovered=hits.length?hits[0].object.userData.part:null;
}
function applyHover(){
 for(const [m,id] of hoverObjects){m.material.emissive.set(hovered===id?'#47b7a4':'#000000');m.material.emissiveIntensity=hovered===id?.65:0;}
 for(const c of chains){const active=hovered===c.part||(hovered==='large'&&c.part==='large-protein')||(hovered==='small'&&c.part==='small-protein');c.cartoon.material.opacity=active?.92:shell?.83:.085;c.cartoon.material.emissive.set(active?'#6fbdad':'#000000');c.cartoon.material.emissiveIntensity=active?.35:0;c.spheres.material.uniforms.alpha.value=active?.94:shell?.65:.07;c.spheres.material.uniforms.tint.value.set(active?'#70d3bd':c.baseColor);}
 catalysis.material.opacity=hovered==='ptc'?1:phase===2?.95:.32;catalysis.scale.setScalar(hovered==='ptc'?1.65:1);
 decode.material.opacity=hovered==='decoding'?1:phase<2?.9:.22;decode.scale.setScalar(hovered==='decoding'?1.5:1);
 renderer.domElement.style.cursor=dragging?'grabbing':hovered?'pointer':'grab';document.body.dataset.hovered=hovered||'';document.body.dataset.pinned=pinnedPart||'';
}
function annotate(){ctx.clearRect(0,0,W,H);labelLayer.hidden=dragging;if(dragging)return;currentLabels=new Set();
 const selected=(id)=>hovered===id?'#167d70':null;
 const lab=(id,name,sub,pos,f,c,g=actors)=>{label(name,sub,pos,H*f,selected(id)||c,g);registerLabel(id,name,sub,f);};
 lab('peptide','Nascent polypeptide','Unfolded chain',exit,.13,'#b57190');
 lab('large','50S · Large subunit','23S + 5S rRNA and proteins',site23.clone().add(new T.Vector3(25,30,0)),.205,'#aa894c',upper);
 lab('ptc','PTC · Peptidyl transferase center','23S rRNA · peptide bond formation',site23,.28,'#aa894c');
 const tr=hovered==='p-trna'?[pRNA,pAnti,'P-site tRNA']:hovered==='e-trna'?[eRNA,eAnti,'E-site tRNA']:[aRNA,aAnti,'Incoming tRNA'];
 lab(hovered==='p-trna'?'p-trna':hovered==='e-trna'?'e-trna':'a-trna',tr[2],'L-shaped RNA · anticodon and 3′-CCA',tr[1],.355,'#348f7c',tr[0].group);
 lab('mrna','mRNA','Codons read in the 5′ → 3′ direction',atom(complex.bound.mRNA,16),.43,'#6987b0',mrna.group);
 lab('small','30S · Small subunit','16S rRNA and proteins',site16.clone().add(new T.Vector3(-20,-20,0)),.505,'#4c978d',lower);
 lab('decoding','Decoding center','16S rRNA checks codon–anticodon pairing',site16,.58,'#4c978d');
 if(hovered==='large-protein'||hovered==='small-protein'){const ch=chains.find(c=>c.part===hovered);ch.cartoon.geometry.computeBoundingSphere();lab(hovered,'Ribosomal proteins','Support structure and function',ch.cartoon.geometry.boundingSphere.center,.65,'#607dac',ch.cartoon.parent);}
 else if(hovered==='ef-tu')lab('ef-tu','EF-Tu','Delivers aminoacyl-tRNA',v(efTrace[Math.floor(efTrace.length/2)].slice(1,4)),.65,'#607dac',efTu);
 else if(hovered==='amino-acid')lab('amino-acid','Amino acid','Carried at the tRNA acceptor end',aa.position,.65,'#b57190');
 for(const [id,button] of labelButtons){button.hidden=!currentLabels.has(id);}
 const x=W*.77,y=H*.735,u=Math.min(unit,1);
 txt('RNA AT WORK',x,y,12*u,'#527e77');
 txt('16S rRNA: checks pairing geometry',x,y+25*u,11*u,'#617b7e');
 txt('23S rRNA: catalyzes peptide transfer',x,y+49*u,11*u,'#aa894c');
 txt('mRNA  5′–U U C–3′',x,y+81*u,11*u,'#6689b7');
 txt('tRNA    3′–A A G–5′',x,y+104*u,11*u,'#398d79');
 for(const [name,pos,g] of [['A',aAnti,aRNA.group],['P',pAnti,pRNA.group],['E',eAnti,eRNA.group]]){if(!g.visible)continue;const q=screen(pos,g);txt(name,q[0]+7,q[1]+11,11,'#54776e');}
 for(const [name,base,offset] of [['5′',first,-65],['3′',last,65]]){const q=screen(v(base.atoms["C4'"]).addScaledVector(direction,offset),mrna.group);txt(name,...q,14,'#829bb8');}
 const q=screen(site23);ctx.strokeStyle=hovered==='ptc'?'#bd882a':'#c4a46b';ctx.lineWidth=hovered==='ptc'?2:1;ctx.beginPath();ctx.arc(q[0],q[1],hovered==='ptc'?14:9,0,Math.PI*2);ctx.stroke();
}

function frame(now){const dt=Math.min(.05,(now-previous)/1000||0);previous=now;if(!paused&&!dragging&&!document.hidden)time+=dt;const t=(time%period)/period;phase=t<.18?0:t<.40?1:t<.56?2:t<.73?3:4;const arrive=smooth(t/.09),accommodate=smooth((t-.20)/.18),transfer=smooth((t-.43)/.10),hybrid=smooth((t-.57)/.13),trans=smooth((t-.76)/.16),restore=smooth((t-.93)/.07);
world.quaternion.copy(rotation);lower.rotation.set(0,0,(hybrid-trans)*.13);head.quaternion.setFromAxisAngle(new T.Vector3(0,1,0),Math.sin(trans*Math.PI)*.23);upper.rotation.set(0,0,0);
aRNA.group.position.copy(direction).multiplyScalar((1-arrive)*65);aRNA.group.quaternion.identity();aRNA.mesh.morphTargetInfluences[0]=1-accommodate;efTu.position.copy(direction).multiplyScalar((1-arrive)*65);efTu.material.opacity=.65*(1-smooth((t-.22)/.1));efTu.visible=t<.34;aRNA.mesh.material.transparent=true;aRNA.mesh.material.opacity=Math.max(.05,arrive);
// Hybrid states move the acceptor arm before the anticodon; the local bend is an illustrative interpolation.
const aHybridQ=new T.Quaternion().setFromUnitVectors(aTip.clone().sub(aAnti).normalize(),pTip.clone().sub(aAnti).normalize());aRNA.group.quaternion.identity().slerp(aHybridQ,hybrid*(1-trans));aRNA.group.position.add(aAnti.clone().sub(aAnti.clone().applyQuaternion(aRNA.group.quaternion)));
const eTip=atom(complex.bound.E,77),pHybridQ=new T.Quaternion().setFromUnitVectors(pTip.clone().sub(pAnti).normalize(),eTip.clone().sub(pAnti).normalize());pRNA.group.quaternion.identity().slerp(pHybridQ,hybrid*(1-trans));pRNA.group.position.copy(pAnti).sub(pAnti.clone().applyQuaternion(pRNA.group.quaternion));if(trans>0){aRNA.group.quaternion.slerp(AP.q,trans);aRNA.group.position.lerp(AP.p,trans);pRNA.group.quaternion.slerp(PE.q,trans);pRNA.group.position.lerp(PE.p,trans);}eRNA.group.position.copy(direction).multiplyScalar(-smooth(t/.2)*37);eRNA.mesh.material.transparent=true;eRNA.mesh.material.opacity=.5*(1-smooth(t/.20));eRNA.group.visible=t<.2;pRNA.mesh.material.transparent=true;pRNA.mesh.material.opacity=1-restore;
const step=pAnti.clone().sub(aAnti);mrna.group.position.copy(step).multiplyScalar(trans);world.position.copy(step).multiplyScalar(-trans*(1-restore)*.35).applyQuaternion(rotation);const activeTip=aTip.clone().applyQuaternion(aRNA.group.quaternion).add(aRNA.group.position);const earlyTip=atom(complex.early.A,76);const at=earlyTip.lerp(aTip,accommodate).applyQuaternion(aRNA.group.quaternion).add(aRNA.group.position);const tip=pTip.clone().lerp(activeTip,transfer);aa.position.copy(at);aa.visible=t<.53;decode.material.opacity=phase<2?.9:.12;catalysis.material.opacity=phase===2?.95:.12;
if(now-lastPeptide>50||lastPeptide<0){const old=peptide.geometry;peptide.geometry=peptideGeometry(tip,time);old.dispose();lastPeptide=now;}
const pairPos=pairGeom.attributes.position;for(let i=0;i<3;i++){const pa=atom(complex.bound.A,36-i,'N1').lerp(atom(complex.early.A,36-i,'N1'),1-accommodate).applyQuaternion(aRNA.group.quaternion).add(aRNA.group.position);const pb=atom(complex.bound.mRNA,15+i,'N3').add(mrna.group.position);pairPos.setXYZ(i*2,pa.x,pa.y,pa.z);pairPos.setXYZ(i*2+1,pb.x,pb.y,pb.z);}pairPos.needsUpdate=true;pairing.computeLineDistances();pairing.visible=arrive>.95&&trans<.05;
for(const c of chains){c.cartoon.visible=mode==='cartoon';c.spheres.visible=mode==='spheres';c.cartoon.material.opacity=shell?.83:.085;c.spheres.material.uniforms.alpha.value=shell?.65:.07;}world.updateMatrixWorld(true);pickPart(now);applyHover();renderer.render(scene,camera);annotate();drawAxes();if(oldPhase!==phase){document.getElementById('phase').textContent=titles[phase];document.getElementById('description').textContent=descriptions[phase];[...document.querySelectorAll('#progress i')].forEach((e,i)=>e.classList.toggle('active',i===phase));oldPhase=phase;}document.body.dataset.phase=String(phase);document.body.dataset.mode=mode;document.body.dataset.ready='true';document.body.dataset.cycle=String(Math.floor(time/period));document.body.dataset.orientation=rotation.toArray().join(',');document.body.dataset.paused=String(paused);requestAnimationFrame(frame);}
for(const b of document.querySelectorAll('[data-mode]'))b.addEventListener('click',()=>{mode=b.dataset.mode;for(const e of document.querySelectorAll('[data-mode]'))e.setAttribute('aria-pressed',String(e===b));});document.getElementById('pause').onclick=()=>{paused=!paused;document.getElementById('pause').textContent=paused?'Resume':'Pause';};document.getElementById('shell').onclick=()=>{shell=!shell;document.getElementById('shell').textContent=shell?'See inside':'Show shell';};function changeZoom(f){zoom=T.MathUtils.clamp(zoom*f,.55,3.5);layout();}document.getElementById('zoom-in').onclick=()=>changeZoom(1.2);document.getElementById('zoom-out').onclick=()=>changeZoom(1/1.2);function reset(){rotation.copy(initial);zoom=1;layout();}document.getElementById('reset').onclick=reset;document.getElementById('sources').onclick=()=>document.getElementById('references').classList.add('open');document.getElementById('close-ref').onclick=()=>document.getElementById('references').classList.remove('open');
function sketchTRNA(){const c=document.getElementById('trna-sketch');c.width=880;c.height=330;const q=c.getContext('2d');q.scale(2,2);q.lineWidth=2;q.strokeStyle='#398f7f';q.beginPath();q.moveTo(97,17);q.lineTo(97,51);q.bezierCurveTo(40,20,20,87,91,80);q.lineTo(91,104);q.bezierCurveTo(66,158,145,160,120,103);q.lineTo(120,80);q.bezierCurveTo(190,87,175,20,114,51);q.lineTo(114,17);q.stroke();for(let i=0;i<4;i++){q.beginPath();q.moveTo(98,24+i*6);q.lineTo(112,24+i*6);q.stroke();}q.fillStyle='#718e89';q.font='11px sans-serif';q.fillText('Acceptor / 3′-CCA',75,12);q.fillText('D loop',24,77);q.fillText('TΨC loop',158,77);q.fillText('Anticodon loop',74,163);q.fillText('2D: cloverleaf',18,146);q.fillText('→ Fold',215,83);q.lineWidth=5;q.beginPath();q.moveTo(309,127);q.lineTo(325,73);q.lineTo(382,38);q.stroke();q.font='12px sans-serif';q.fillText('3D: L shape',289,157);q.font='10px sans-serif';q.fillText('Anticodon',280,143);q.fillText('3′-CCA',363,24);q.fillText('Elbow',335,84);}sketchTRNA();
const canvas=renderer.domElement;canvas.style.touchAction='none';canvas.style.cursor='grab';canvas.addEventListener('pointerdown',e=>{if(e.button!==0)return;hovered=null;dragging=true;lastPointer=[e.clientX,e.clientY];canvas.setPointerCapture(e.pointerId);canvas.style.cursor='grabbing';});canvas.addEventListener('pointermove',e=>{hoverPointer={x:e.clientX,y:e.clientY};if(!dragging)return;const delta=new T.Vector3(e.clientY-lastPointer[1],e.clientX-lastPointer[0],0),n=delta.length();if(n)rotation.premultiply(new T.Quaternion().setFromAxisAngle(delta.normalize(),n*.006)).normalize();lastPointer=[e.clientX,e.clientY];});canvas.addEventListener('pointerleave',()=>{hoverPointer=null;hovered=null;});function release(){dragging=false;canvas.style.cursor='grab';}for(const event of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(event,release);canvas.addEventListener('wheel',e=>{e.preventDefault();changeZoom(Math.exp(-e.deltaY*.001));},{passive:false});canvas.addEventListener('dblclick',reset);window.addEventListener('keydown',e=>{if(e.key==='Escape'){pinnedPart=null;labelHover=null;document.activeElement?.blur();reset();document.getElementById('references').classList.remove('open');}});window.addEventListener('resize',resize);document.getElementById('status').remove();resize();requestAnimationFrame(frame);
})();
